[package]
name = "konachan-wallpaper"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
