[package]
name = "konachan-wallpaper"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.56"
once_cell = "1.10"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "fs"] }
futures-util = "0.3"
